CREATE SEQUENCE PS_ALARMS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE alarm (
    id INTEGER AUTO_INCREMENT DEFAULT PS_EMERGENCIES_SEQ.nextval NOT NULL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
);