CREATE SEQUENCE ALARMS_SEQ_PS_V2
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE ALARMS_PS_V2 (
    ALARM_ID INTEGER DEFAULT ALARMS_SEQ_PS_V2.nextval NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    STATUS_ALARM VARCHAR(100) NOT NULL,
    DT_ALARM TIMESTAMP NOT NULL
)