name: CI Production

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # ou 'zulu', 'adopt', etc.
        java-version: '17'

    - name: Grant execute permission for Maven Wrapper
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Build Docker image
      run: docker build -t publicsecurityfiap.azurecr.io/public_security:prod .

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: publicsecurityfiap.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image
      run: docker push publicsecurityfiap.azurecr.io/public_security:prod

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: publicsecurity
        images: publicsecurityfiap.azurecr.io/public_security:prod